services:
  kafka:
    image: 'bitnamilegacy/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami/kafka'
    # This single line now handles all your configuration
    env_file: .env
volumes:
  kafka_data:
    driver: local
